### ISSUE TITLE
[20.04] - Window borders do not apply

### ISSUE THREAD

**Issue by Maksat-Rsymbetov** [lah7/Ambiant-MATE-Colours#34]
### Describe the problem
When the theme is generated via python script window borders are not applied and some ugly one applied instead

### Expected behaviour
Window borders work 

### Which themes are affected?

- Ambiant-MATE
- Ambiant-MATE-Dark
 (Tested only this ones)

### Screenshots
![image](https://user-images.githubusercontent.com/90955239/159911933-1ad39b19-6d35-40a9-8f98-63154aed9f73.png)

### Release Version
Ubuntu MATE 20.04

**Comment by Maksat-Rsymbetov** [comment]
sorry for showing not appropriate screenshot. Here is the appropriate one
![image](https://user-images.githubusercontent.com/90955239/159912350-6e1c09a0-62c5-4dcf-9282-8a6465001002.png)

**Comment by lah7** [comment]
I couldn't replicate. Although, I used `ubuntu-mate-artwork` from an older point in history, as the theme has been removed upstream. This can be done as follows:

```bash
cd ubuntu-mate-artwork
git checkout 50d84002dbcbc455e287286b35c7a88a226d3a60
# Run ./generate-ambiant-mate-colour.py as usual
```

That would be the workaround for now. The theme is now [available here](https://github.com/lah7/Ambiant-MATE/) instead, but I have some work to do in both repositories.

If that doesn't work, what compositor are you using? The issue looks similiar to the Compiz days, where the window borders would not display unless they were copied system-wide (`/usr/share/themes`)

**Comment by Maksat-Rsymbetov** [comment]
Thank you for the reply. Copied themes to the system directory you mentioned, and everything works well now.
And yes, I'm using compiz
